#+TITLE: BowChain
#+AUTHOR: Dylan Winters

* Overview
Process a bow chain dataset using =BowChain_master(cruiseName,deploymentName)=.

~BowChain_master.m~ is structured as follows:

** Cruise and deployment configuration

The cruise's configuration function is called using ~get_config.m~. This fills
the cruise's config structure with global default options from
~config_default.m~ and checks deployments for missing options.

** Deployment processing
   
Each deployment is processed sequentially with the following steps:

1) Sensor setup (~preproc_setup.m~)
   - The user-defined sensor serial numbers are passed into
     ~get_sensor_info.m~. This function acts as a database containing
     processing instructions for different sensor types.
   - If the instrument type is known and an associated raw datafile is found,
     the sensor gets an entry in ~config.sensors~ containing parsing
     instructions and an output .mat file name.

2) File conversion (~preproc_raw2mat.m~)

   - Using the information gathered in ~preproc_setup~, each sensor's raw
     datafiles are convered to a .mat format. This step is skipped if .mat
     files already exist.

3) Load data

   - Each sensor's .mat file is loaded using ~proc_load_mat.m~. This creates a
     ~data~ cell array with raw sensor data in each cell.

4) Sample data onto a uniformly-spaced time base using ~proc_grid_init~.

5) Calibrate sensor clocks and pressure sensors
   - Clocks are calibrated using ~proc_time_offsets.m~. The
     ~config.time_offset_method~ and related fields control what this function
     does.
   - Pressure sensors are calibrated with ~proc_pressure_cal~ if the
     ~config.zero_pressure_interval~ field is defined.

6) Apply positional offsets to measurements
   - ~proc_chain_model.m~ uses known instrument positions and measured
     pressure data to compute positional offsets for each measurement. This
     adds an ~x~ and ~z~ field to the gridded data structure.
      

* Configuration

** Deployment configuration

Within the [[file:Code/][Code]] directory, cruise-specific folders contain information needed to
locate and process deployment data. Each cruise needs a ~<cruise>_config~ file
that returns a structure containing configuration information for each
deployment.

For example, [[file:Code/Cruise_ArcticMix/config_ArcticMix.m][Cruse_ArcticMix/config_ArcticMix.m]] creates a structure containing
deployment information for the ArcticMix cruise. Only one deployment entry is
shown below:

#+BEGIN_SRC matlab
  %% Deployment setup
  config(1).name = 'MooringToIce'
  config(1).dir_raw = '/path/to/raw/data/11sept_1900_recovery';
  config(1).dn_range = datenum([...
      '09-Sep-2015 21:49:40';
      '10-Sep-2015 08:36:14']);
  config(1).sensor_sn ={'00451';'100161';'100154';'060281';'00407';'100160';...
                        '100153';'00445';'100157';'00422';'100159';'100158';'00442';...
                        '100162';'03253';'100155';'00392';'00372';'060280';'100156'};
  config(1).sensor_pos = [0 1 2 3 4 5 6 7 8 9 11 12 13 14 14.5 15 16 17 18 19];
#+END_SRC

*** Deployment configuration options

Base parameters
| Field                         | Description                                      | Default                 |
|-------------------------------+--------------------------------------------------+-------------------------|
| config.name                   | deployment name                                  |                         |
| config.dir.raw                | raw deployment data directory                    |                         |
| config.sensor_sn              | cell array of sensor serial number strings       |                         |
| config.sensor_pos             | vector of sensor positions                       |                         |
| config.dn_range               | time interval for deployment                     |                         |
| config.freq_base              | frequency of gridded output data                 | 2 Hz                    |
| config.time_offset.method     | method for sensor clock corrections              | 'none'                  |
| config.zero_pressure_interval | time interval for zero-pressure calibration      | no pressure calibration |
| config.chain_model            | model to use for instrument position corrections | 'cm_straight'           |

Some configuration options require additional fields in the ~config~ structure:
| Field                     | Value         | Additional Required Field | Description                                 |
|---------------------------+---------------+---------------------------+---------------------------------------------|
| config.time_offset_method | 'cohere'      | config.cohere_interval    | Interval to use for clock calibration       |
| config.time_offset_method | 'known_drift' | config.time_synched       | Time (datenum,UTC) that clocks were synched |
| config.time_offset_method | 'known_drift' | config.drift              | Measured clock drift on recovery            |
 
*** Locating instrument data

Data organization might change between cruises, but is likely consistent for
each cruise. By default, it is assumed that all raw data files (from every
instrument) reside in the deployments ~config.dir_raw~ folder.

Within each cruise folder, an optional ~sensor_dirs_<cruise>~ function can be
defined if more complex organization is required. This function takes a
deployment's config structure entry and an instrument serial number as input and
returns a new directory name for that particular instrument's raw data folder.

Again using the ArctixMix deployment example:

In the case of the /MooringToIce/ deployment, raw instrument data was organized
into instrument-specific directories within the ~config.dir_raw~ folder. The
[[file:Code/Cruise_ArcticMix/sensor_dirs_ArcticMix.m][sensor_dirs_ArcticMix]] function is thus straightforward - we just need to append
the serial number to the deployment's ~config.dir_raw~ field.

#+BEGIN_SRC matlab
  function sensor_dir = sensor_dirs_ArcticMix(config,sn)
  sensor_dir = fullfile(config.dir_raw,sn);
#+END_SRC

Note that since the ~config~ structure contains the deployment's name, and a
single instrument serial number is given as input, this function allows for
extreme flexibility down to the level of instrument-specific folders on a
per-deployment basis. This is hopefully not required with good data
organization!


** Instrument configuration

Each instrument is linked to an instrument type via its serial number, and each
instrument type is linked to a parsing function and a raw data file extension.
This is all done in [[file:Code/get_sensor_info.m][get_sensor_info.m]], which takes a serial number string as
input.

*Any instruments that I have not encountered will not be included in this list!*
Fortunately, associating serial numbers to instruments can be easily done by
modifying the first few lines of [[file:Code/get_sensor_info.m][get_sensor_info]] to include new serial numbers:

#+BEGIN_SRC matlab
  %% Instrument serial numbers

  % SBE39
  sbe39 = {'03253'};

  % SBE56
  sbe56 = {'00372','00392','00407','00422','00442','00445','00451'};

  % RBR Solo
  rbr_solo = {'100153','100154','100155','100156','100157','100158',...
              '100159','100160','100161','100162'};

  % RBR Concerto
  rbr_concerto = {'060280','060281'};
#+END_SRC

This method allows finding and parsing raw data to be generalized to a function
of instrument serial number, but requires wrappers around low-level instrument
parsing functions so that the output data format is consistent across all
instrument types. This makes adding a new instrument type require some
additional modificatons.

The following files in the [[file:Code/ParseFunctions/][Code/ParseFunctions/]] directory are all examples of
such "wrapper" functions:

- [[file:Code/ParseFunctions/parse_rbr_concerto.m]]
- [[file:Code/ParseFunctions/parse_rbr_solo.m]]
- [[file:Code/ParseFunctions/parse_sbe39.m]]
- [[file:Code/ParseFunctions/parse_sbe56.m]]

These functions are simple, but necessary - they call low-level raw
data parsing functions and restructure the output to facilitate later data
processing.

See the latter half of [[file:Code/get_sensor_info.m][get_sensor_info.m]] for associations between instrument
types and parsing functions.

** Setting configuration options with fill_defaults

This section can be safely ignored, but might be useful.

The [[file:Code/fill_defaults.m][fill_defaults]] function can be used at any stage of setup to apply a set of
default options to a cruise's deployment configuration structure. It is used in
the core code to apply the default ~freq_base~ and ~chain_model~ parameters
shown in the table above. Only options that are undefined will be filled -
existing options will not be overwritten.
