#+TITLE: BowChain
#+AUTHOR: Dylan Winters

* Overview
Process a bow chain dataset using =BowChain_master(cruiseName,deploymentName)=.

* Configuration

** Cruise- and deployment-specific configuration

Within the [[file:Code/][Code]] directory, cruise-specific folders contain information needed to
locate and process deployments. Each cruise needs a configuration file in its
corresponding folder.

For example, [[file:Code/Cruise_ArcticMix/config_ArcticMix.m][Cruse_ArcticMix/config_ArcticMix.m]] contains information about bow
chain deployments on the ArcticMix cruise. Within the configuration file is a
switch statement that sets processing options depending on the given deployment
name:

#+BEGIN_SRC matlab
%% Deployment-specific options
switch dep
  case 'MooringToIce'
    config.dir_deployment = '11sept_1900_recovery';
    config.dn_range = datenum([...
        '09-Sep-2015 21:49:40';
        '10-Sep-2015 08:36:14']);
    config.sensor_sn ={'00451';'100161';'100154';'060281';'00407';'100160';...
                       '100153';'00445';'100157';'00422';'100159';'100158';'00442';...
                       '100162';'03253';'100155';'00392';'00372';'060280';'100156'};
    config.sensor_pos = [0 1 2 3 4 5 6 7 8 9 11 12 13 14 14.5 15 16 17 18 19];
end
#+END_SRC

For now, only the "MooringToIce" deployment is configured.


** Required configuration options 

| Option           | Description                                                                    |
|------------------+--------------------------------------------------------------------------------|
| =freq_base=      | Frequency of the output gridded data                                           |
| =dir_raw=        | Full path to the base directory containing raw data                            |
| =dir_deployment= | Subdirectory within =dir_raw= containing data logged during the deployment    |
| =dn_range=       | Range of datenums for the deployment start and end times                       |
| =sensor_sn=      | Cell array of sensor serial numbers (as strings)                               |
| =sensor_pos=     | Nominal positions of sensors along the chain                                   |
| =chain_model=    | Model used to accout for the bow chain's shape                                 |

An error will be thrown before processing begins if any of these options have
not been specified.

** Setting configuration options

Configuration options are first loaded from [[file:Code/config_default.m][config_default.m]]. Currently, this
only sets a default base frequency and chain model name:

#+BEGIN_SRC matlab
% config_default.m
config.freq_base = 2;
config.chain_model = 'cm_straight';
#+END_SRC

Deployment-specific options are set as shown above for the "MooringToIce"
deployment. Any options defined prior to the deployment name switch will be
overwritten by deployment-specific configuration.

The order in which options are read results in the following priority (higher
priorities overwrite lower priorities):

1. Cruise-wide options defined after the deployment name switch
2. Deployment-specific options defined in the deployment name switch
3. Cruise-wide options defined prior to the deployment name switch
4. Default options defined in [[file:Code/config_default.m][config_default.m]]
   

* Chain Shape models

** [[Org/cm_straight.org][cm_straight]]
